/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface LabelSettings {
  'barcode2Layout' : LayoutSettings,
  'widthMm' : bigint,
  'heightMm' : bigint,
  'serialText1Layout' : LayoutSettings,
  'serialText2Layout' : LayoutSettings,
  'spacing' : bigint,
  'barcodeType' : string,
  'prefixMappings' : Array<[string, PrefixMapping]>,
  'barcodeHeight' : bigint,
  'barcode1Layout' : LayoutSettings,
  'titleLayout' : LayoutSettings,
}
export interface LayoutSettings {
  'x' : bigint,
  'y' : bigint,
  'height' : bigint,
  'scale' : number,
  'width' : bigint,
  'fontSize' : bigint,
}
export interface PrefixMapping { 'title' : string, 'labelType' : string }
export interface PrintJob {
  'id' : bigint,
  'owner' : [] | [Principal],
  'labelType' : string,
  'leftSerial' : string,
  'printCount' : bigint,
  'timestamp' : Time,
  'prefix' : string,
  'rightSerial' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLabelSettings' : ActorMethod<[], LabelSettings>,
  'getPrintHistory' : ActorMethod<[], Array<PrintJob>>,
  'getPrintHistoryByLabelType' : ActorMethod<[], Array<PrintJob>>,
  'getPrintHistoryByTimestamp' : ActorMethod<[], Array<PrintJob>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'increasePrintCount' : ActorMethod<[bigint], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitPrintJob' : ActorMethod<[string, string, string], boolean>,
  'updateLabelSettings' : ActorMethod<[LabelSettings], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];