/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const LayoutSettings = IDL.Record({
  'x' : IDL.Int,
  'y' : IDL.Int,
  'height' : IDL.Int,
  'scale' : IDL.Float64,
  'width' : IDL.Int,
  'fontSize' : IDL.Nat,
});
export const PrefixMapping = IDL.Record({
  'title' : IDL.Text,
  'labelType' : IDL.Text,
});
export const LabelSettings = IDL.Record({
  'barcode2Layout' : LayoutSettings,
  'widthMm' : IDL.Nat,
  'heightMm' : IDL.Nat,
  'serialText1Layout' : LayoutSettings,
  'serialText2Layout' : LayoutSettings,
  'spacing' : IDL.Nat,
  'barcodeType' : IDL.Text,
  'prefixMappings' : IDL.Vec(IDL.Tuple(IDL.Text, PrefixMapping)),
  'barcodeHeight' : IDL.Nat,
  'barcode1Layout' : LayoutSettings,
  'titleLayout' : LayoutSettings,
});
export const Time = IDL.Int;
export const PrintJob = IDL.Record({
  'id' : IDL.Nat,
  'owner' : IDL.Opt(IDL.Principal),
  'labelType' : IDL.Text,
  'leftSerial' : IDL.Text,
  'printCount' : IDL.Nat,
  'timestamp' : Time,
  'prefix' : IDL.Text,
  'rightSerial' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLabelSettings' : IDL.Func([], [LabelSettings], ['query']),
  'getPrintHistory' : IDL.Func([], [IDL.Vec(PrintJob)], ['query']),
  'getPrintHistoryByLabelType' : IDL.Func([], [IDL.Vec(PrintJob)], ['query']),
  'getPrintHistoryByTimestamp' : IDL.Func([], [IDL.Vec(PrintJob)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'increasePrintCount' : IDL.Func([IDL.Nat], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitPrintJob' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
  'updateLabelSettings' : IDL.Func([LabelSettings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const LayoutSettings = IDL.Record({
    'x' : IDL.Int,
    'y' : IDL.Int,
    'height' : IDL.Int,
    'scale' : IDL.Float64,
    'width' : IDL.Int,
    'fontSize' : IDL.Nat,
  });
  const PrefixMapping = IDL.Record({
    'title' : IDL.Text,
    'labelType' : IDL.Text,
  });
  const LabelSettings = IDL.Record({
    'barcode2Layout' : LayoutSettings,
    'widthMm' : IDL.Nat,
    'heightMm' : IDL.Nat,
    'serialText1Layout' : LayoutSettings,
    'serialText2Layout' : LayoutSettings,
    'spacing' : IDL.Nat,
    'barcodeType' : IDL.Text,
    'prefixMappings' : IDL.Vec(IDL.Tuple(IDL.Text, PrefixMapping)),
    'barcodeHeight' : IDL.Nat,
    'barcode1Layout' : LayoutSettings,
    'titleLayout' : LayoutSettings,
  });
  const Time = IDL.Int;
  const PrintJob = IDL.Record({
    'id' : IDL.Nat,
    'owner' : IDL.Opt(IDL.Principal),
    'labelType' : IDL.Text,
    'leftSerial' : IDL.Text,
    'printCount' : IDL.Nat,
    'timestamp' : Time,
    'prefix' : IDL.Text,
    'rightSerial' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLabelSettings' : IDL.Func([], [LabelSettings], ['query']),
    'getPrintHistory' : IDL.Func([], [IDL.Vec(PrintJob)], ['query']),
    'getPrintHistoryByLabelType' : IDL.Func([], [IDL.Vec(PrintJob)], ['query']),
    'getPrintHistoryByTimestamp' : IDL.Func([], [IDL.Vec(PrintJob)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'increasePrintCount' : IDL.Func([IDL.Nat], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitPrintJob' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
    'updateLabelSettings' : IDL.Func([LabelSettings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };